// Remote image URLs stored in Supabase storage (signed URLs)
// Keep these centralized so pages can reference images from the DB/storage.
export const calender = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/calender.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2NhbGVuZGVyLnN2ZyIsImlhdCI6MTc2MzA3MDc5NCwiZXhwIjoxNzk0NjA2Nzk0fQ.016H67-UnEcKbm7C6KRMkYBDB0RUu06nOBn2eVof64o'
export const chess = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/chess.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2NoZXNzLnN2ZyIsImlhdCI6MTc2MzA3MDgwMywiZXhwIjoxNzk0NjA2ODAzfQ.268nNKPb8sO5Kuh3GYASNDj9rYyz0hbJVPJEk0KjKN8'
export const lawka = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/lawka.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2xhd2thLmpwZWciLCJpYXQiOjE3NjMwNzA4MTUsImV4cCI6MTc5NDYwNjgxNX0.G9xcnw4zkC15_4LHmPvHNc6CNQeii-QRg21DopFV7r0'
export const locationImg = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/location.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2xvY2F0aW9uLnN2ZyIsImlhdCI6MTc2MzA3MDgyNSwiZXhwIjoxNzk0NjA2ODI1fQ.Aq2qi1PAbPWimgbTUqXtGRS5HgsOvsTLPCPYatQCXD8'
export const people = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/people.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3Blb3BsZS5zdmciLCJpYXQiOjE3NjMwNzA4MzUsImV4cCI6MTc5NDYwNjgzNX0.AmecBLG0LB-FTxYEiVlNqUXohU6zt2Ypl2ZNaVDL8vg'
export const pilka = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/pilka.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3BpbGthLmpwZyIsImlhdCI6MTc2MzA3MDg0MiwiZXhwIjoxNzk0NjA2ODQyfQ.E3ag_YFnId2ipP4ckEj8dVlh5wCicW_gqLgSP7EfJHo'
export const puchar = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/puchar.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3B1Y2hhci5qcGciLCJpYXQiOjE3NjMwNzA4NTEsImV4cCI6MTc5NDYwNjg1MX0.Jg1hYU2yscboWfQ-VsPLo9ktZW5U15h-K27bNy5qGOY'
export const soccer = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/soccer.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3NvY2Nlci5zdmciLCJpYXQiOjE3NjMwNzA4NTcsImV4cCI6MTc5NDYwNjg1N30.EmMzsnK5j4oA0Fit_kYIU2cr2HMeSE_xeDo8P_FYwDU'
export const szatnia = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/szatnia.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3N6YXRuaWEuanBnIiwiaWF0IjoxNzYzMDcwODYzLCJleHAiOjE3OTQ2MDY4NjN9.bBFeTjUOnPi0LicIkQ6h7VlT9s_uBtJ80Np6qRTnXL0'
export const team = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/team.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3RlYW0uc3ZnIiwiaWF0IjoxNzYzMDcwODcwLCJleHAiOjE3OTQ2MDY4NzB9.fZ7WpnMlXbECWz5tKqYLOJxyf50PuEaKSl8iLxDt9M4'
export const google = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/icons8-google.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2ljb25zOC1nb29nbGUuc3ZnIiwiaWF0IjoxNzYzNDg4MDk5LCJleHAiOjE3OTUwMjQwOTl9.zuRLwz4zuF-OIxOQHIxSqsHrzAFjyngAt3dFeLhR564'
export const logo = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/logo.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2xvZ28uc3ZnIiwiaWF0IjoxNzYzNDg4NDI5LCJleHAiOjE3OTUwMjQ0Mjl9.Bzx_oOsMyaNFnJfMz-VK8Gw5jfXXxyyh2znQoFwy4qg'

// Team logos for CreateTeam page
export const logo_team1 = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/team_logo/cat-animal-svgrepo-com.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ0ZWFtX2xvZ28vY2F0LWFuaW1hbC1zdmdyZXBvLWNvbS5zdmciLCJpYXQiOjE3NjM0OTM0NjIsImV4cCI6MTc5NTAyOTQ2Mn0.tOitiR3CWkzj1JcEHVQM6qlhxI_tQyIKHAvRxNeAwR0'
export const logo_team2 = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/team_logo/cat-kitty-kitten-feline-svgrepo-com.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ0ZWFtX2xvZ28vY2F0LWtpdHR5LWtpdHRlbi1mZWxpbmUtc3ZncmVwby1jb20uc3ZnIiwiaWF0IjoxNzYzNDkzNDY5LCJleHAiOjE3OTUwMjk0Njl9.s2YSVdUGoCO8ChIJYmbEO1R2YAP1gNNdmboy7l2sE9I'
export const logo_team3 = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/team_logo/donkey-ass-domesticated-animal-mule-svgrepo-com.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ0ZWFtX2xvZ28vZG9ua2V5LWFzcy1kb21lc3RpY2F0ZWQtYW5pbWFsLW11bGUtc3ZncmVwby1jb20uc3ZnIiwiaWF0IjoxNzYzNDkzNDc2LCJleHAiOjE3OTUwMjk0NzZ9.1DZeowEZ2LU81kHAUKBGQTu7g3325BpIG3l_GIQZ4uo'
export const logo_team4 = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/team_logo/duck-nature-bird-target-svgrepo-com.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ0ZWFtX2xvZ28vZHVjay1uYXR1cmUtYmlyZC10YXJnZXQtc3ZncmVwby1jb20uc3ZnIiwiaWF0IjoxNzYzNDkzNDg0LCJleHAiOjE3OTUwMjk0ODR9.W4IVof21D52fcpJFESvniX7rqsRWN6vVAkM7P_0I-i8'
export const logo_team5 = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/team_logo/octopus-animal-cephalopod-svgrepo-com.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ0ZWFtX2xvZ28vb2N0b3B1cy1hbmltYWwtY2VwaGFsb3BvZC1zdmdyZXBvLWNvbS5zdmciLCJpYXQiOjE3NjM0OTM0OTAsImV4cCI6MTc5NTAyOTQ5MH0.XIpp9f2IvDWmR5pFwslaniZ1oVHmjkECLTuxqkWWNT8'
export const logo_team6 = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/team_logo/tree-nature-oak-svgrepo-com.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ0ZWFtX2xvZ28vdHJlZS1uYXR1cmUtb2FrLXN2Z3JlcG8tY29tLnN2ZyIsImlhdCI6MTc2MzQ5MzUxMCwiZXhwIjoxNzk1MDI5NTEwfQ.DlzXbYtMhopSvtF-EnFcCp3TnDEOD2VJqPFonbBcRB4'
export const logo_team7 = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/team_logo/turtle-slow-slowly-svgrepo-com.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ0ZWFtX2xvZ28vdHVydGxlLXNsb3ctc2xvd2x5LXN2Z3JlcG8tY29tLnN2ZyIsImlhdCI6MTc2MzQ5MzUxNywiZXhwIjoxNzk1MDI5NTE3fQ.qqIAQA9SzgL76ljQqOjEV1umqzzbmBG60GqRcl7jqBg'
export const logo_team8 = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/team_logo/unicorn-legend-valuation-myth-svgrepo-com.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ0ZWFtX2xvZ28vdW5pY29ybi1sZWdlbmQtdmFsdWF0aW9uLW15dGgtc3ZncmVwby1jb20uc3ZnIiwiaWF0IjoxNzYzNDkzNTIxLCJleHAiOjE3OTUwMjk1MjF9.IWB0JQdG51RnPPr7tyhmOA1TWlaiCDiYN-rHlQvxcos'
export const logo_team9 = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/team_logo/walking-bear-bear-wild-wildlife-svgrepo-com.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ0ZWFtX2xvZ28vd2Fsa2luZy1iZWFyLWJlYXItd2lsZC13aWxkbGlmZS1zdmdyZXBvLWNvbS5zdmciLCJpYXQiOjE3NjM0OTM1MjksImV4cCI6MTc5NTAyOTUyOX0.T55-gFw8ePvitXvoTh1EWk6Iz4cODalME393O2a6ijg'
export const logo_team10 = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/team_logo/walking-dragon-legend-myth-folklore-svgrepo-com.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ0ZWFtX2xvZ28vd2Fsa2luZy1kcmFnb24tbGVnZW5kLW15dGgtZm9sa2xvcmUtc3ZncmVwby1jb20uc3ZnIiwiaWF0IjoxNzYzNDkzNTQwLCJleHAiOjE3OTUwMjk1NDB9.A3TLkAKEs9lvKkVhHWtnsxjfzwzzgxBZGr5uCcRSBnw'

export default {
  calender,
  chess,
  lawka,
  locationImg,
  people,
  pilka,
  puchar,
  soccer,
  szatnia,
  team,
  google,
  logo,
  logo_team1,
  logo_team2,
  logo_team3,
  logo_team4,
  logo_team5,
  logo_team6,
  logo_team7,
  logo_team8,
  logo_team9,
  logo_team10,
}
