// Remote image URLs stored in Supabase storage (signed URLs)
// Keep these centralized so pages can reference images from the DB/storage.
export const calender = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/calender.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2NhbGVuZGVyLnN2ZyIsImlhdCI6MTc2MzA3MDc5NCwiZXhwIjoxNzk0NjA2Nzk0fQ.016H67-UnEcKbm7C6KRMkYBDB0RUu06nOBn2eVof64o'
export const chess = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/chess.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2NoZXNzLnN2ZyIsImlhdCI6MTc2MzA3MDgwMywiZXhwIjoxNzk0NjA2ODAzfQ.268nNKPb8sO5Kuh3GYASNDj9rYyz0hbJVPJEk0KjKN8'
export const lawka = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/lawka.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2xhd2thLmpwZWciLCJpYXQiOjE3NjMwNzA4MTUsImV4cCI6MTc5NDYwNjgxNX0.G9xcnw4zkC15_4LHmPvHNc6CNQeii-QRg21DopFV7r0'
export const locationImg = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/location.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2xvY2F0aW9uLnN2ZyIsImlhdCI6MTc2MzA3MDgyNSwiZXhwIjoxNzk0NjA2ODI1fQ.Aq2qi1PAbPWimgbTUqXtGRS5HgsOvsTLPCPYatQCXD8'
export const people = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/people.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3Blb3BsZS5zdmciLCJpYXQiOjE3NjMwNzA4MzUsImV4cCI6MTc5NDYwNjgzNX0.AmecBLG0LB-FTxYEiVlNqUXohU6zt2Ypl2ZNaVDL8vg'
export const pilka = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/pilka.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3BpbGthLmpwZyIsImlhdCI6MTc2MzA3MDg0MiwiZXhwIjoxNzk0NjA2ODQyfQ.E3ag_YFnId2ipP4ckEj8dVlh5wCicW_gqLgSP7EfJHo'
export const puchar = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/puchar.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3B1Y2hhci5qcGciLCJpYXQiOjE3NjMwNzA4NTEsImV4cCI6MTc5NDYwNjg1MX0.Jg1hYU2yscboWfQ-VsPLo9ktZW5U15h-K27bNy5qGOY'
export const soccer = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/soccer.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3NvY2Nlci5zdmciLCJpYXQiOjE3NjMwNzA4NTcsImV4cCI6MTc5NDYwNjg1N30.EmMzsnK5j4oA0Fit_kYIU2cr2HMeSE_xeDo8P_FYwDU'
export const szatnia = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/szatnia.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3N6YXRuaWEuanBnIiwiaWF0IjoxNzYzMDcwODYzLCJleHAiOjE3OTQ2MDY4NjN9.bBFeTjUOnPi0LicIkQ6h7VlT9s_uBtJ80Np6qRTnXL0'
export const team = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/team.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL3RlYW0uc3ZnIiwiaWF0IjoxNzYzMDcwODcwLCJleHAiOjE3OTQ2MDY4NzB9.fZ7WpnMlXbECWz5tKqYLOJxyf50PuEaKSl8iLxDt9M4'
export const google = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/icons8-google.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2ljb25zOC1nb29nbGUuc3ZnIiwiaWF0IjoxNzYzNDg4MDk5LCJleHAiOjE3OTUwMjQwOTl9.zuRLwz4zuF-OIxOQHIxSqsHrzAFjyngAt3dFeLhR564'
export const logo = 'https://sxzelvgmcmsevdygunnt.supabase.co/storage/v1/object/sign/logo/logo.svg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wYzM1ZWZlMS1lMGFkLTQ2YmQtYmYxZC1lNjljNTc2NDQ5NjUiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJsb2dvL2xvZ28uc3ZnIiwiaWF0IjoxNzYzNDg4NDI5LCJleHAiOjE3OTUwMjQ0Mjl9.Bzx_oOsMyaNFnJfMz-VK8Gw5jfXXxyyh2znQoFwy4qg'

export default {
  calender,
  chess,
  lawka,
  locationImg,
  people,
  pilka,
  puchar,
  soccer,
  szatnia,
  team,
  google,
  logo,
}
